### ISSUE TITLE
Use once_cell

### ISSUE THREAD

**Issue by lxrst** [mrlazy1708/tqdm#15]
once_cell's Lazy is a newer alternative to lazy_static that all the cool kids use. It does have a hard std requirement iirc, but I don't think that should matter here.
I'd be happy to implement this myself.

**Comment by mrlazy1708** [comment]
Hi lxrst,

Thanks, that's a good point (didn't know about `once_cell`!)

I see it has low MSRV so it should be a good alternative. Yeah it would be great if you could implement this in a PR. I just made some refactoring / added some features from py tqdm. Hopefully this doesn't cause trouble to your implementation, if you've started.

**Comment by mrlazy1708** [comment]
Merged, thanks!
