### ISSUE TITLE
tqdm does not support a collection of async functions

### ISSUE THREAD

**Issue by timvancann** [mrlazy1708/tqdm#18]
There is no way (or I didn't find it in the docs) to wrap `tqdm` around a vector of futures that are passed into `join_all`
```rust
use futures::future::join_all;

async fn do_something_long() {}

async fn run() {
    let futurez = (1..10).map(|_| do_something_long());
    join_all(futurez);
}
```

Am I missing something; is there a way around this; are there plans for supporting this?

**Comment by mrlazy1708** [comment]
If I'm understanding correctly, you mean the following code

```rust
use tqdm::tqdm;

async fn do_something(_: usize) {
    tokio::time::sleep(core::time::Duration::from_secs_f64(3.0)).await;
}

#[tokio::main]
async fn main() {
    let futurez: Vec<_> = (1..100).map(do_something).collect();
    futures::future::join_all(tqdm(futurez.into_iter())).await;
}
```

shows a progress bar that ends immediately, but it makes more sense to have it tracking the progress of each future?

**Comment by mrlazy1708** [comment]
If that's the case, do you think the solution would be a `tqdm_async` (or maybe `tqdm::async::tqdm`), that is designed specifically for `Iterator<Item = some Future>`? The iterator now consumes everything upon `.await` and produces reordered items

**Comment by mrlazy1708** [comment]
Finally have some time to work this out: 5b0992f140d1f8b694d3c77ca5b276acdf3d075b. lmk what you think @timvancann
