### ISSUE TITLE
No Windows support

### ISSUE THREAD

**Issue by oersted** [mrlazy1708/tqdm#3]
`tqdm` is not supported in Windows due to using `termion` as a dependency. `crossterm` is the recommended alternative with has a similar API.

**Comment by mrlazy1708** [comment]
Thanks for mentioning! I also want to remove `lazy_static` as dependency since `rust 1.63` introduced const Mutex. I'll get back to this later.

**Comment by mrlazy1708** [comment]
I rewrote it today with `crossterm`. It should be working on Windows now. Closing
