### ISSUE TITLE
Add a "tqdm.write" like method

### ISSUE THREAD

**Issue by Aubrey-Liu** [mrlazy1708/tqdm#8]
Currently, if I want to print some information within the loop, there will be something like:
```rust
for i in tqdm(x.iter()) {
  // do something
  println!("anything");
}
```
However, this `println` will interfere with the progress bar, and it's like:

<img width="756" alt="Screenshot 2023-04-04 at 15 08 05" src="https://user-images.githubusercontent.com/72335144/229714944-e6f06d99-468a-4849-8f37-1d2f08464426.png">

and a desirable output will be like:

<img width="756" alt="Screenshot 2023-04-04 at 15 10 23" src="https://user-images.githubusercontent.com/72335144/229715422-aaeb112e-1959-4775-8eab-2b72d7f0dd70.png">

Therefore, print the message through a tqdm.write method might be a good idea.

**Comment by mrlazy1708** [comment]
Looking into this
